Repository atom/find-and-replace, pull requests merged in 2019-01, with the labels that each got.

#1061 Remove hardcoded fonts so that search view always use Atom’s font
  styles/find-and-replace.less
Labels: triaged

#988 Don't watch TextEditors outside of the current project in Project Find
  lib/project/results-model.js
  spec/fixtures/project/one-long-line.coffee
  spec/fixtures/project/sample.coffee
  spec/fixtures/project/sample.js
  spec/project-find-view-spec.js
  spec/results-model-spec.js
  spec/results-view-spec.js
Labels: needs-review

#1069 Understand observeEmbeddedTextEditor to follow embedded TextEditor changes
  lib/find.coffee
  spec/find-spec.js
  spec/item/deferred-editor-item.js
Labels: work-in-progress
